name: Deploy Docker App to ECS

on:
  push:
    branches:
      - main   # make sure your main branch matches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIAQQ4Z4MCIZTMNFZUN }}
          aws-secret-access-key: ${{ secrets.Xq4326onX/ALGTH2lMDgXPbM88gDUqqXB9P+k4Gv }}
          aws-region: ${{ secrets.us-east-1 }}     # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t my-app ./app

      # 4️⃣ Login to ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.us-east-1 }} \
          | docker login --username AWS --password-stdin ${{ secrets.036293075089 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com

      # 5️⃣ Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag my-app:latest ${{ secrets.036293075089 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com/${{ secrets.my-app }}:latest

      # 6️⃣ Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.036293075089 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com/${{ secrets.my-app }}:latest

      # 7️⃣ Update ECS Service
      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-update-task-definition@v1
        with:
          cluster: my-ecs-cluster               # Terraform ECS cluster name
          service: my-app-service               # Terraform ECS service name
          task-definition: my-app-task          # Terraform ECS task family
          image: ${{ secrets.036293075089 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com/${{ secrets.my-app }}:latest
